pipeline {
  agent any

   stages {

    stage ('Health check') {
     steps {
             sleep 30

       httpRequest responseHandle: 'NONE', timeout: 2500, url: 'http://172.17.0.7:80', validResponseCodes: '200', consoleLogResponseBody: true
     }
    }
   }
}
