pipeline {
   agent any

   stages {

    stage ('Health check') {
     steps {
             sleep 30

       httpRequest responseHandle: 'NONE', timeout: 2500, url: 'http://172.20.128.13:8080/sample.web.service-0.0.1-SNAPSHOT/users', validResponseCodes: '200', consoleLogResponseBody: true
     }
    }
   }
   
   post {
    failure { 
     mail bcc: '', body: 'ERROR CD: Project name -> sample.web.service', cc: '', from: '', replyTo: '', subject: "ERROR CD: Project name -> sample.web.service", to: 'fferide.celik@gmail.com, admin.admin@gmail.com';
    }
   }  

}
