pipeline {
  agent any

   stages {

    stage ('Run') {
     steps {
             sh '''
                cd /home/Ansible
                ansible-playbook playbook.yml
                '''
     }
    }
   }
}   
