---

- name: prod server start
  hosts: localhost
  connection: local
  remote_user: root

  tasks:
    - name: include variables
      include_vars: vars.yml

    - name: Create Container
      docker_container:
        name: "{{ name }}"
        image: "{{ image }}"
        ports:
          - "{{ src_port }}:{{ dest_port }}"
        networks:
          - name: devops-pipeline_st
            ipv4_address: 172.20.128.13
        state: started

    - name: copy .war file from slave to prod server
      command: docker cp /tmp/sample-web-service/target/sample.web.service-0.0.1-SNAPSHOT.war prod:/usr/local/tomcat/webapps

    - name: tomcat service restart
      command: docker restart prod
