version: '3.1'
services:

   # Prod server
   tomcat:
      image: tomcat:8.5-jre8-alpine
      container_name: prod
      hostname: prod
      ports:
         - '5555:8080'
      networks:
         st:
            ipv4_address: 172.20.128.16
    
    # Jenkins master
    jenkins:
       image: jenkins-master
       container_name: jenkins
       ports:
           - '8080:8080'
           - '50000:50000'
       networks:
          st:
             ipv4_address: 172.20.128.17

    # Jenkins slave node
    jenkins-slave:
       image: jenkins-slave
       container_name: jenkins-slave
       restart: always
       environment:
          - 'JENKINS_URL=http://jenkins:8080'
       volumes:
          - /var/run/docker.sock:/var/run/docker.sock  # Expose the docker daemon in the container
       depends_on:
          - jenkins
       networks:
          st:
             ipv4_address: 172.20.128.18

networks:
  st:
    ipam:
      config:
        - subnet: 172.20.0.0/16
          ip_range: 172.28.5.0/24
