pipeline {
    agent any

    stages {
        stage('Build') {
            steps {
                echo "Compiling..."
                sh 'mvn -B -DskipTests clean package'
            }
        }
    }
}
